# Site settings
title: flyzy小站
SEOTitle: flyzy小站 | flyzy小站，GitHub Pages分部
header-img: img/home-bg.jpg
email: flyzy2005@gmail.com
description: "flyzy小站GitHub分站~"
keyword: "技术分享,科学上网,建站教程"
url: "https://flyzy2005.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
csdn_username: wf632856695
#weibo_username:     flyzy2005
#zhihu_username:     flyzy2005
github_username:    flyzy2005
#twitter_username:  flyzy2005
#facebook_username:  flyzy2005



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "学习ing~</br>主页：<a href=\"https://www.flyzy2005.cn\">flyzy小站</a>"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "flyzy小站",
        href: "https://www.flyzy2005.cn",
        description: "flyzy小站总部，欢迎来给我留言~"
    }
]
